# Generated by Django 3.1 on 2020-08-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200831_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='snippet',
            field=models.CharField(default='click link above to read post', max_length=255),
        ),
    ]
