# Generated by Django 3.1 on 2020-08-31 11:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200831_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='snippetbody',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
