# Generated by Django 3.1 on 2020-08-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_snippetbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='snippet',
        ),
    ]
