# Generated by Django 3.1 on 2020-08-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_article_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(default='this is test'),
        ),
    ]
