# Generated by Django 3.1 on 2020-08-31 14:54

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200831_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
